apiVersion: v1
kind: Service
metadata:
  name: crm
  annotations:
    servicePatterns: "crm"
    isDiscoverable: "true"
spec:
  selector:
    app: crm
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP